version: "3"

services:
  api:
    build:
      context: ./api
    volumes:
      - "./api/src:/srv/src"
    ports:
      - "3000:3000"
  withdraw-notes-calculator:
    build:
      context: ./withdraw-notes-calculator
    volumes:
      - "./withdraw-notes-calculator/src:/srv/src"
    ports:
      - "3001:3000"
  frontend:
    build:
      context: ./frontend
    volumes:
      - "./frontend/src:/srv/src"
    ports:
      - "4200:4200"

